// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY8WvUDe9QoecP7UZUZ3J72S6PZwJAId0',
    appId: '1:26806036925:web:af08bb7d3dd9b4e76c8ad4',
    messagingSenderId: '26806036925',
    projectId: 'cargas-mc',
    authDomain: 'cargas-mc.firebaseapp.com',
    storageBucket: 'cargas-mc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwjG0n3ArsxX6O2lw_eGERhQEkISkXfv8',
    appId: '1:26806036925:android:1e5e573cb515a38c6c8ad4',
    messagingSenderId: '26806036925',
    projectId: 'cargas-mc',
    storageBucket: 'cargas-mc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY8WvUDe9QoecP7UZUZ3J72S6PZwJAId0',
    appId: '1:26806036925:web:822ff6fa3c902a2d6c8ad4',
    messagingSenderId: '26806036925',
    projectId: 'cargas-mc',
    authDomain: 'cargas-mc.firebaseapp.com',
    storageBucket: 'cargas-mc.firebasestorage.app',
  );
}
